-- Migration: Add timeline column to video_chapters + expose it in uploadable_chapters
-- Created: 2026-06-14
-- Depends on: 007_update_uploadable_chapters_order.sql (uploadable_chapters view),
--             youtube_chapters_schema.sql (video_chapters table)
--
-- Persists the per-chapter timeline (list of {time, speaker, content} key moments,
-- with ABSOLUTE source-video timestamps) so the congress_youtube_chapter_uploader
-- DAG can render YouTube chapter markers in the video description. The timeline is
-- generated by summarize_one_chunk but was previously discarded before reaching the DB.
--
-- Idempotent: ADD COLUMN IF NOT EXISTS + CREATE OR REPLACE VIEW are safe to re-run.
-- The migration runner runs `SET search_path TO {schema}, public` before executing,
-- so table/view names are intentionally UNQUALIFIED (applies to development and production).
--
-- Example (development): psql ... -c "SET search_path TO development, public;" -f 010_add_timeline_column.sql
-- Example (production):  psql ... -c "SET search_path TO production, public;"  -f 010_add_timeline_column.sql

-- Step 1: Add the timeline column (JSONB, default empty array).
ALTER TABLE video_chapters
    ADD COLUMN IF NOT EXISTS timeline JSONB DEFAULT '[]'::jsonb;

-- Step 2: Recreate uploadable_chapters to expose vc.timeline.
-- Definition copied from 007_update_uploadable_chapters_order.sql + vc.timeline.
CREATE OR REPLACE VIEW uploadable_chapters AS
SELECT
    vc.chapter_id,
    vc.video_id,
    ysv.video_title AS source_video_title,
    ysv.session_number,
    ysv.session_date,
    vc.title AS chapter_title,
    vc.description,
    vc.duration_minutes,
    vc.speakers,
    vc.topics,
    vc.timeline,
    vc.start_time,
    vc.end_time,
    vc.relevance_score,
    vc.speaker_relevance_points,
    vc.topic_relevance_points,
    vc.public_interest_points,
    vc.scoring_reasoning,
    vc.key_speakers,
    vc.is_current_topic,
    vc.is_uploaded_to_youtube,
    vc.created_at,
    CURRENT_DATE - DATE(vc.created_at) AS days_since_created
FROM video_chapters vc
JOIN youtube_source_videos ysv ON vc.video_id = ysv.video_id
WHERE
    vc.is_uploaded_to_youtube = FALSE
    AND vc.relevance_score >= 2
ORDER BY
    ysv.session_date DESC NULLS LAST,
    vc.relevance_score DESC,
    vc.created_at DESC;
