name: Sync Main to Dev

on:
  pull_request:
    types:
      - closed

jobs:
  sync-main-to-dev:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante para obtener todo el historial

      # Set up Git user
      - name: Set up Git User
        uses: fregante/setup-git-user@v2

      # Fetch all branches and tags
      - name: Fetch all branches and tags
        run: git fetch --all

      # Check if branches are up to date
      - name: Check if branches are up to date
        shell: bash
        id: checkBranches
        run: |
          git checkout dev
          BASE=$(git merge-base origin/main HEAD || echo "")
          if [ -z "$BASE" ]; then
            echo "mergeRequired=true" >> $GITHUB_ENV
          elif [ "$BASE" = "$(git rev-parse origin/main)" ]; then
            echo "mergeRequired=false" >> $GITHUB_ENV
          else
            echo "mergeRequired=true" >> $GITHUB_ENV
          fi

      # Merge main into dev if needed
      - name: Merge main into dev
        if: env.mergeRequired == 'true'
        shell: bash
        run: |
          git merge --ff-only origin/main
          if [ $? -ne 0 ]; then
            echo "Merge conflict detected. Please resolve conflicts manually."
            exit 1
          fi

      # Push changes to dev branch
      - name: Push changes
        if: env.mergeRequired == 'true'
        run: git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}